### ISSUE TITLE
State shape

### ISSUE THREAD

**Issue by Rolandkuku** [esgiprojetninja/workaway#9]
L'idée c'est d'avoir un flowType pour décrire le state d'une app redux de CRUD. Du coup, on doit pouvoir gérer n'importe quel type d'entité (user, accomodation, mission...) avec ce state.

- [x] CREATE
- [x] READ
- [x] UPDATE
- [x] DELETE

**Create:**

Je dois avoir accès à un objet "placeholder" qui va décrire l'entité que je veux sauvegarder. En plus de l'objet en lui-même, j'ai besoin de méta-data: l'objet est-il en train de sauvegarder ?

**READ**

J'ai besoin d'avoir accès à une liste des objets et au détail d'un objet en particulier. Pour anticiper d'éventuels problèmes de perf (coucou @dydyFos), on peut imaginer deux listes: une `data = [1, 2, ..., 100]` qui va contenir les id des objets et une `byID = [1: {objet}, 2: {objet}, .., 1000: {objet}]` qui va contenir les entités triées par id. Comme ça, on peut accéder directement à l'entité qui nous intéresse : `prout = byID[98]`. Il faut un attribut `isLoading`.

**UPDATE**

On peut éventuellement se servir du placeholder du CREATE. On pourra différencier un nouvel objet d'un objet modifié avec son id : s'il n'en a pas, c'est qu'il est en cours de création.

**UPDATE**

Pretty straight forward: il faut un attribut `isLoading`.

**Comment by Rolandkuku** [comment]
```
declare type User = {
    name: string,
    id: string
};

declare type Mission = {
    name: string,
    id: string,
    address: string
}

declare type CRUDStateType = {
    data: Array<number>,
    byID: Array<User | Mission>,
    isLoading: boolean,
    current: {
        entity: User | Mission,
        isLoading: boolean
    }
}
```

**Comment by Rolandkuku** [comment]
`decls/entityFlowTypes.js`:

```
// @flow

export type UserType = {
    name: string,
    id: string
};

export type MissionType = {
    name: string,
    id: string,
    address: string
};
```
`decls/flowTypes.js`

```
// @flow
import {
    UserType,
    MissionType,
} from "./entityFlowTypes";

export type CrudStateType = {
    data: Array<number>,
    byID: Map<number, UserType | MissionType>,
    isLoading: boolean,
    current: {
        entity: UserType | MissionType,
        isLoading: boolean
    }
};
```

**Comment by dydyFos** [comment]
```
declare type UserType = {
    name: string,
    id: string
};

declare type MissionType = {
    name: string,
    id: string,
    address: string
}

type DataModelTypes = {
  user: UserType
  mission: MissionType,
};

type State$Values = $Values<DataModelTypes>;

declare type CRUDStateType = {
    data: Array<number>,
    byID: State$Values,    // modified line
    isLoading: boolean,
    current: {
        entity: User | Mission,
        isLoading: boolean
    }
}```

**Comment by Rolandkuku** [comment]
T'es sûr que c'est lisible ?

**Comment by Rolandkuku** [comment]
Ou sinon `State$Values` => `DataModelTypes$Values` ?

**Comment by Rolandkuku** [comment]
```
type DataModelsType = {
  user: UserType,
  mission: MissionType
};

type DataModelsValuesType = $Values<DataModelsType>;

export type CrudStateType = {
    data: Array<number>,
    byID: Map<number, DataModelsValuesType>,
    isLoading: boolean,
    current: {
        entity: DataModelsValuesType,
        isLoading: boolean
    }
};
```
